---
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
  - name: ansible
    privilege: 15
    role: network-admin
    # password: ansible
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

  - name: arista
    privilege: 15
    role: network-admin
    # password: arista
    sha512_password: "$6$7WhvEi5Ce5f5Ut3z$Ethmha7rb710RKsaVteusVOuNP1Utfjzse58xxbgiZp4MF0fp7BX5lAw8yBgv/HWCihVomuCSrsJx8wKnJ7Tm1"
# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default

daemon_terminattr:
  cvaddrs:
    - 10.73.1.238:9910
  cvauth:
    method: token
    token_file: "/tmp/token"
  cvobscurekeyfile: false
  cvsourceip: '{{ ansible_host }}'
  cvvrf: default
  cvgnmi: true
  disable_aaa: false
  ingestexclude: '/Sysdb/cell/1/agent,/Sysdb/cell/2/agent'
  smashexcludes: 'ale,flexCounter,hardware,kni,pulse,strata'

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

timezone: Europe/Paris

ntp:
  local_interface:
    name: Management0
    vrf: default
  servers:
    - name: fr.pool.ntp.org
      preferred: true
      local_interface: Management0
      vrf: default
      burst: true
      iburst: true
    - name: uk.pool.ntp.org
      local_interface: Management0
      vrf: default
      burst: true
      iburst: true

# dns domain
dns_domain: anta.example

aaa_authorization:
  exec:
    default: local
