---
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
  - name: arista
    privilege: 15
    role: network-admin
    # password: arista
    sha512_password: "$6$7WhvEi5Ce5f5Ut3z$Ethmha7rb710RKsaVteusVOuNP1Utfjzse58xxbgiZp4MF0fp7BX5lAw8yBgv/HWCihVomuCSrsJx8wKnJ7Tm1"

mgmt_gateway: 192.168.0.1
mgmt_interface: Management0
mgmt_interface_vrf: default

cvp_instance_ips: [192.168.0.5]
terminattr_smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
terminattr_ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
cvp_token_file: /mnt/flash/cv-onboarding-token

name_servers:
  - 8.8.8.8

timezone: Europe/Paris

ntp:
  local_interface:
    name: Management0
    vrf: default
  servers:
    - name: fr.pool.ntp.org
      preferred: true
      local_interface: Management0
      vrf: default
      burst: true
      iburst: true
    - name: uk.pool.ntp.org
      local_interface: Management0
      vrf: default
      burst: true
      iburst: true


custom_structured_configuration_aaa_authorization:
  exec:
    default: local

custom_structured_configuration_aaa_authentication:
  login:
  policies:
    local:
      allow_nopassword: true
