---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# TODO: enabled auto update for pre-commit
# ci:
#  autoupdate_commit_msg: "ci: pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: docs/.*.svg|containerlab/topology.clab.drawio
      - id: end-of-file-fixer
        exclude: docs/.*.svg|containerlab/topology.clab.drawio
      - id: check-added-large-files
        exclude: tests/data/.*$
      - id: check-merge-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - name: Check and insert license on Python files
        id: insert-license
        files: .*\.py$
        args:
          - --license-filepath
          - .github/license-short.txt
          - --use-current-year
          - --allow-past-years
          - --fuzzy-match-generates-todo
          - --no-extra-eol

      - name: Check and insert license on Markdown files
        id: insert-license
        files: .*\.md$
        exclude: ^avd/documentation/.*
        args:
          - --license-filepath
          - .github/license-short.txt
          - --use-current-year
          - --allow-past-years
          - --fuzzy-match-generates-todo
          - --comment-style
          - '<!--|  ~|  -->'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: Run Ruff linter
        args: [--fix]
      - id: ruff-format
        name: Run Ruff formatter

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
        exclude: ^docs/topology.clab.svg

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        name: Check Markdown files style.
        args:
          - --config=.github/markdownlint.yaml
          - --ignore-path=.github/markdownlintignore
          - --fix
